<a href="https://colab.research.google.com/github/preetibhatt29/OIBSIP-/blob/main/All_Classifier_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_moons, make_circles, make_classification
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
import pandas as pd

In [ ]:
h = 0.02  # step size in the mesh

names = [
    "Nearest Neighbors",
    "Linear SVM",
    "RBF SVM",
    "Gaussian Process",
    "Decision Tree",
    "Random Forest",
    "Neural Net",
    "AdaBoost",
    "Naive Bayes",
    "QDA",
]

classifiers = [
    KNeighborsClassifier(3),
    SVC(kernel="linear", C=0.025),
    SVC(gamma=2, C=1),
    GaussianProcessClassifier(1.0 * RBF(1.0)),
    DecisionTreeClassifier(max_depth=5),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
    MLPClassifier(alpha=1, max_iter=1000),
    AdaBoostClassifier(),
    GaussianNB(),
    QuadraticDiscriminantAnalysis(),
]


In [ ]:
X, y = make_classification(
    n_features=2, n_redundant=0, n_informative=2, random_state=1, n_clusters_per_class=1
)
rng = np.random.RandomState(2)
X += 2 * rng.uniform(size=X.shape)
linearly_separable = (X, y)

datasets = [
    make_moons(noise=0.3, random_state=0),
    make_circles(noise=0.2, factor=0.5, random_state=1),
    linearly_separable,
]




In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#Load Data

df = pd.read_csv('/content/drive/My Drive/OASIS/Iris.csv')

In [ ]:
df = df.drop(columns = ['Id'])
df = df.drop(columns = ['Species'])
df.head()


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species1
0            5.1           3.5            1.4           0.2         0
1            4.9           3.0            1.4           0.2         0
2            4.7           3.2            1.3           0.2         0
3            4.6           3.1            1.5           0.2         0
4            5.0           3.6            1.4           0.2         0

In [ ]:

X = df.drop(['Species1'], axis='columns')
Y = df.Species1

from sklearn.model_selection import train_test_split
#train, test = train_test_split(df, test_size=0.25, stratify=df['Species1'])

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, stratify=df['Species1'])
#x_train= train.drop(['Species1'], axis='columns')
#y_train = train.Species1
#x_test= test.drop(['Species1'], axis='columns')
#y_test = test.Species1
print("==================================================")
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(112, 4)
(112,)
(38, 4)
(38,)


In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
from pickleshare import print_function
# iterate over datasets
i=1
# iterate over classifiers
for name, clf in zip(names, classifiers):
    clf.fit(x_train, y_train)
    y_pred=clf.predict(x_test)
    score = clf.score(x_test, y_test)
    i=i+1
    print("%s = %.2f \t" %(name, score))
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred)) #shows all
    print("++++++++++++++++++++++++++++++++++++++++++++++++")



Nearest Neighbors = 0.97 	
[[13  0  0]
 [ 0 13  0]
 [ 0  1 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.93      1.00      0.96        13
           2       1.00      0.92      0.96        12

    accuracy                           0.97        38
   macro avg       0.98      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38

++++++++++++++++++++++++++++++++++++++++++++++++
Linear SVM = 0.95 	
[[13  0  0]
 [ 0 13  0]
 [ 0  2 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.87      1.00      0.93        13
           2       1.00      0.83      0.91        12

    accuracy                           0.95        38
   macro avg       0.96      0.94      0.95        38
weighted avg       0.95      0.95      0.95        38

++++++++++++++++++++++++++++++++++++++++++++++++
RBF SVM = 1.00 	
[[